version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html          # HTML, CSS, JS
      - ./backend:/var/www/html                   # PHP
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro # Nginx config
      - ./project/assets:/var/www/html/assets
    depends_on:
      - php
    networks:
      - my_network

  php:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - my_network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
