version: '3.8'

services:
  frontend:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./php:/var/www/html

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  frontend-build:
    build:
      context: ./frontend   # <<--- แก้ให้ build เป็น mapping (object)
    ports:
      - "8080:80"           # <<--- เปลี่ยน port ไม่ให้ชน
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
